query GetMyProfile @auth(level: USER, insecureReason: "This operation is safe to expose to all logged in users.") {
  user(key: {id_expr: "auth.uid"}) {
    id
    displayName
    email
    learningLevel
    profilePictureUrl
    targetLanguage {
      name
      code
    }
    userSettings_on_user {
      difficultyLevel
      enableSoundPronunciation
      wordTranslationPercentage
    }
  }
}

mutation CreateNewWordList($name: String!, $description: String, $isPublic: Boolean!) @auth(level: USER, insecureReason: "This operation is safe to expose to all logged in users.") {
  wordList_insert(data: {
    name: $name,
    description: $description,
    isPublic: $isPublic,
    ownerId_expr: "auth.uid",
    createdAt_expr: "request.time"
  }) {
    id
  }
}

query GetPublicWordLists @auth(level: PUBLIC, insecureReason: "This operation is safe to expose to the public") {
  wordLists(where: {isPublic: {eq: true}}, orderBy: [{createdAt: DESC}]) {
    id
    name
    description
    owner {
      displayName
    }
  }
}

mutation AddWordToWordList($wordListId: UUID!, $vocabularyWordId: UUID!, $notes: String) @auth(level: USER, insecureReason: "This operation is safe to expose to all logged in users.") {
  wordListEntry_insert(data: {
    wordListId: $wordListId,
    vocabularyWordId: $vocabularyWordId,
    notes: $notes,
    addedAt_expr: "request.time"
  }) {
    wordListId
    vocabularyWordId
  }
}